apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-management

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - mongodb.yaml
  - postgres.yaml
  - redis.yaml
  - user-service.yaml
  - task-service.yaml
  - notification-service.yaml
  - frontend.yaml
  - ingress.yaml
